#set_property PACKAGE_PIN T4 [get_ports flash_clk]
# Pines y estandares de niveles logicos
#Clock
set_property PACKAGE_PIN Y18 [get_ports CLOCK_50]
set_property IOSTANDARD LVCMOS33 [get_ports CLOCK_50]

#Leds y Botones
set_property PACKAGE_PIN H13 [get_ports LED]
set_property IOSTANDARD LVCMOS33 [get_ports LED]

#set_property PACKAGE_PIN G15 [get_ports testled2]
#set_property IOSTANDARD LVCMOS33 [get_ports testled2]

#set_property PACKAGE_PIN G15 [get_ports BTN]
#set_property IOSTANDARD LVCMOS33 [get_ports BTN]
#set_property PULLUP true [get_ports BTN]

#Keyboard and mouse
set_property PACKAGE_PIN U1 [get_ports PS2_CLKA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLKA]
set_property PULLUP true [get_ports PS2_CLKA]
set_property PACKAGE_PIN T1 [get_ports PS2_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
set_property PULLUP true [get_ports PS2_DATA]
set_property PACKAGE_PIN P4 [get_ports PS2_CLKB]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLKB]
set_property PACKAGE_PIN N5 [get_ports PS2_DATB]
set_property PULLUP true [get_ports PS2_DATB]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATB]

# Video output
set_property PACKAGE_PIN V18 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property PACKAGE_PIN P19 [get_ports VGA_VS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]
set_property PACKAGE_PIN W21 [get_ports {VGA_B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[7]}]
set_property PACKAGE_PIN W19 [get_ports {VGA_B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[6]}]
set_property PACKAGE_PIN AA20 [get_ports {VGA_B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[5]}]
set_property PACKAGE_PIN Y21 [get_ports {VGA_B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[4]}]
set_property PACKAGE_PIN AB21 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN T20 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN T6 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN U5 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]

set_property PACKAGE_PIN W17 [get_ports {VGA_R[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[7]}]
set_property PACKAGE_PIN AA19 [get_ports {VGA_R[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[6]}]
set_property PACKAGE_PIN AB20 [get_ports {VGA_R[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[5]}]
set_property PACKAGE_PIN V20 [get_ports {VGA_R[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[4]}]
set_property PACKAGE_PIN Y19 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN P20 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN T5 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN R6 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

set_property PACKAGE_PIN W22 [get_ports {VGA_G[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[7]}]
set_property PACKAGE_PIN AA21 [get_ports {VGA_G[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[6]}]
set_property PACKAGE_PIN Y22 [get_ports {VGA_G[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[5]}]
set_property PACKAGE_PIN AB22 [get_ports {VGA_G[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[4]}]
set_property PACKAGE_PIN W20 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN V17 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN V4 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN V5 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]

#Audio
set_property PACKAGE_PIN V19 [get_ports AUDIO_L]
set_property IOSTANDARD LVCMOS33 [get_ports AUDIO_L]
set_property PACKAGE_PIN U17 [get_ports AUDIO_R]
set_property IOSTANDARD LVCMOS33 [get_ports AUDIO_R]
#set_property PACKAGE_PIN B1 [get_ports ear]
#set_property IOSTANDARD LVCMOS33 [get_ports ear]

#set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVCMOS33} [get_ports SCLK]
#set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports LRCLK]
#set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVCMOS33} [get_ports SDIN]

#Joystick
#set_property PACKAGE_PIN V2 [get_ports joy_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports joy_clk]
#set_property PACKAGE_PIN U2 [get_ports joy_load_n]
#set_property IOSTANDARD LVCMOS33 [get_ports joy_load_n]
#set_property PACKAGE_PIN W2 [get_ports joy_data]
#set_property IOSTANDARD LVCMOS33 [get_ports joy_data]

#set_property PACKAGE_PIN AB5 [get_ports xjoy_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports xjoy_clk]
#set_property PACKAGE_PIN AA4 [get_ports xjoy_load_n]
#set_property IOSTANDARD LVCMOS33 [get_ports xjoy_load_n]
#set_property PACKAGE_PIN AA6 [get_ports xjoy_data]
#set_property IOSTANDARD LVCMOS33 [get_ports xjoy_data]

#SRAM
#set_property PACKAGE_PIN U18 [get_ports {SRAM_ADDR[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[0]}]
#set_property PACKAGE_PIN AB18 [get_ports {SRAM_ADDR[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[1]}]
#set_property PACKAGE_PIN P15 [get_ports {SRAM_ADDR[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[2]}]
#set_property PACKAGE_PIN T18 [get_ports {SRAM_ADDR[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[3]}]
#set_property PACKAGE_PIN R17 [get_ports {SRAM_ADDR[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[4]}]
#set_property PACKAGE_PIN P14 [get_ports {SRAM_ADDR[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[5]}]
#set_property PACKAGE_PIN AB3 [get_ports {SRAM_ADDR[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[6]}]
#set_property PACKAGE_PIN Y3 [get_ports {SRAM_ADDR[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[7]}]
#set_property PACKAGE_PIN R14 [get_ports {SRAM_ADDR[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[8]}]
#set_property PACKAGE_PIN T3 [get_ports {SRAM_ADDR[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[9]}]
#set_property PACKAGE_PIN P16 [get_ports {SRAM_ADDR[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[10]}]
#set_property PACKAGE_PIN AA3 [get_ports {SRAM_ADDR[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[11]}]
#set_property PACKAGE_PIN P17 [get_ports {SRAM_ADDR[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[12]}]
#set_property PACKAGE_PIN AB2 [get_ports {SRAM_ADDR[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[13]}]
#set_property PACKAGE_PIN AA18 [get_ports {SRAM_ADDR[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[14]}]
#set_property PACKAGE_PIN Y2 [get_ports {SRAM_ADDR[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[15]}]
#set_property PACKAGE_PIN Y1 [get_ports {SRAM_ADDR[16]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[16]}]
#set_property PACKAGE_PIN W1 [get_ports {SRAM_ADDR[17]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[17]}]
#set_property PACKAGE_PIN V3 [get_ports {SRAM_ADDR[18]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[18]}]
#set_property PACKAGE_PIN G2 [get_ports {SRAM_ADDR[19]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_ADDR[19]}]

#set_property PACKAGE_PIN N17 [get_ports {SRAM_DQ[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[0]}]
#set_property PACKAGE_PIN AA5 [get_ports {SRAM_DQ[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[1]}]
#set_property PACKAGE_PIN N14 [get_ports {SRAM_DQ[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[2]}]
#set_property PACKAGE_PIN N13 [get_ports {SRAM_DQ[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[3]}]
#set_property PACKAGE_PIN R16 [get_ports {SRAM_DQ[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[4]}]
#set_property PACKAGE_PIN AA1 [get_ports {SRAM_DQ[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[5]}]
#set_property PACKAGE_PIN AB1 [get_ports {SRAM_DQ[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[6]}]
#set_property PACKAGE_PIN U3 [get_ports {SRAM_DQ[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[7]}]
#set_property PACKAGE_PIN N2 [get_ports {SRAM_DQ[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[8]}]
#set_property PACKAGE_PIN P2 [get_ports {SRAM_DQ[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[9]}]
#set_property PACKAGE_PIN P1 [get_ports {SRAM_DQ[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[10]}]
#set_property PACKAGE_PIN R1 [get_ports {SRAM_DQ[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[11]}]
#set_property PACKAGE_PIN K6 [get_ports {SRAM_DQ[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[12]}]
#set_property PACKAGE_PIN L1 [get_ports {SRAM_DQ[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[13]}]
#set_property PACKAGE_PIN M1 [get_ports {SRAM_DQ[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[14]}]
#set_property PACKAGE_PIN K4 [get_ports {SRAM_DQ[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SRAM_DQ[15]}]

#set_property PACKAGE_PIN N15 [get_ports SRAM_WE_N]
#set_property IOSTANDARD LVCMOS33 [get_ports SRAM_WE_N]

#set_property PACKAGE_PIN E1 [get_ports SRAM_OE_N]
#set_property IOSTANDARD LVCMOS33 [get_ports SRAM_OE_N]

#set_property PACKAGE_PIN U20 [get_ports SRAM_UB_N]
#set_property IOSTANDARD LVCMOS33 [get_ports SRAM_UB_N]
#set_property PACKAGE_PIN N4 [get_ports SRAM_LB_N]
#set_property IOSTANDARD LVCMOS33 [get_ports SRAM_LB_N]

#SD
#set_property PACKAGE_PIN M6 [get_ports SD_CK]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_CK]
#set_property PACKAGE_PIN L5 [get_ports SD_nCS]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_nCS]
#set_property PACKAGE_PIN M5 [get_ports SD_DO]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_DO]
#set_property PULLUP true [get_ports SD_DO]
#set_property PACKAGE_PIN L4 [get_ports SD_DI]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_DI]

#UART
#set_property PACKAGE_PIN N3 [get_ports uart_rx]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
#set_property PACKAGE_PIN D1 [get_ports uart_tx]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
#set_property PACKAGE_PIN H5 [get_ports uart_rts]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_rts]
#set_property PACKAGE_PIN J2 [get_ports uart_gpio0]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_gpio0]
#set_property PACKAGE_PIN L6 [get_ports uart_reset]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_reset]

#MIDDLE BOARD COMMS
#set_property PACKAGE_PIN V8 [get_ports mb_uart_rx]
#set_property IOSTANDARD LVCMOS33 [get_ports mb_uart_rx]
#set_property PACKAGE_PIN W9 [get_ports mb_uart_tx]
#set_property IOSTANDARD LVCMOS33 [get_ports mb_uart_tx]

#I2C
#set_property PACKAGE_PIN Y7 [get_ports i2c_sda]
#set_property IOSTANDARD LVCMOS33 [get_ports i2c_sda]
#set_property PACKAGE_PIN AB6 [get_ports i2c_scl]
#set_property IOSTANDARD LVCMOS33 [get_ports i2c_scl]

#MIDI
#set_property PACKAGE_PIN Y8 [get_ports WSBD]
#set_property IOSTANDARD LVCMOS33 [get_ports WSBD]
#set_property PACKAGE_PIN AA8 [get_ports CLKBD]
#set_property IOSTANDARD LVCMOS33 [get_ports CLKBD]
#set_property PACKAGE_PIN AB8 [get_ports DABD]
#set_property IOSTANDARD LVCMOS33 [get_ports DABD]
#set_property PACKAGE_PIN AB7 [get_ports MIDI_OUT]
#set_property IOSTANDARD LVCMOS33 [get_ports MIDI_OUT]

#Flash SPI
#set_property IOSTANDARD LVCMOS33 [get_ports flash_clk]
#set_property PACKAGE_PIN T19 [get_ports flash_cs_n]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_cs_n]
#set_property PACKAGE_PIN R22 [get_ports flash_miso]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_miso]
#set_property PULLUP true [get_ports flash_miso]
#set_property PACKAGE_PIN P22 [get_ports flash_mosi]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_mosi]
#set_property PACKAGE_PIN P21 [get_ports flash_wp]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_wp]
#set_property PACKAGE_PIN R21 [get_ports flash_hold]
#set_property IOSTANDARD LVCMOS33 [get_ports flash_hold]

#
# SDRAM signals
#
set_property PACKAGE_PIN G20 [get_ports SDRAM_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_CLK]
set_property PACKAGE_PIN H22 [get_ports SDRAM_CKE]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_CKE]

set_property PACKAGE_PIN L21 [get_ports SDRAM_DQMH]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQMH]
set_property PACKAGE_PIN M18 [get_ports SDRAM_DQML]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQML]

#set_property PACKAGE_PIN L21 [get_ports SDRAM_DQmh_n]
#set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQmh_n]
#set_property PACKAGE_PIN M18 [get_ports SDRAM_DQml_n]
#set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_DQml_n]

set_property PACKAGE_PIN L18 [get_ports SDRAM_nCAS]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_nCAS]
set_property PACKAGE_PIN K19 [get_ports SDRAM_nRAS]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_nRAS]
set_property PACKAGE_PIN J17 [get_ports SDRAM_nWE]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_nWE]
set_property PACKAGE_PIN N22 [get_ports SDRAM_nCS]
set_property IOSTANDARD LVCMOS33 [get_ports SDRAM_nCS]

set_property PACKAGE_PIN H20 [get_ports {SDRAM_BA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_BA[1]}]
set_property PACKAGE_PIN J19 [get_ports {SDRAM_BA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_BA[0]}]

set_property PACKAGE_PIN J22 [get_ports {SDRAM_A[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[12]}]
set_property PACKAGE_PIN J15 [get_ports {SDRAM_A[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[11]}]
set_property PACKAGE_PIN K21 [get_ports {SDRAM_A[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[10]}]
set_property PACKAGE_PIN H15 [get_ports {SDRAM_A[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[9]}]
set_property PACKAGE_PIN G18 [get_ports {SDRAM_A[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[8]}]
set_property PACKAGE_PIN G17 [get_ports {SDRAM_A[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[7]}]
set_property PACKAGE_PIN H14 [get_ports {SDRAM_A[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[6]}]
set_property PACKAGE_PIN J14 [get_ports {SDRAM_A[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[5]}]
set_property PACKAGE_PIN G16 [get_ports {SDRAM_A[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[4]}]
set_property PACKAGE_PIN J20 [get_ports {SDRAM_A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[3]}]
set_property PACKAGE_PIN J21 [get_ports {SDRAM_A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[2]}]
set_property PACKAGE_PIN K22 [get_ports {SDRAM_A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[1]}]
set_property PACKAGE_PIN H19 [get_ports {SDRAM_A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_A[0]}]

set_property PACKAGE_PIN M13 [get_ports {SDRAM_DQ[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[0]}]
set_property PACKAGE_PIN L13 [get_ports {SDRAM_DQ[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[1]}]
set_property PACKAGE_PIN L16 [get_ports {SDRAM_DQ[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[2]}]
set_property PACKAGE_PIN M15 [get_ports {SDRAM_DQ[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[3]}]
set_property PACKAGE_PIN K16 [get_ports {SDRAM_DQ[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[4]}]
set_property PACKAGE_PIN L14 [get_ports {SDRAM_DQ[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[5]}]
set_property PACKAGE_PIN K17 [get_ports {SDRAM_DQ[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[6]}]
set_property PACKAGE_PIN K14 [get_ports {SDRAM_DQ[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[7]}]
set_property PACKAGE_PIN M21 [get_ports {SDRAM_DQ[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[8]}]
set_property PACKAGE_PIN M22 [get_ports {SDRAM_DQ[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[9]}]
set_property PACKAGE_PIN N19 [get_ports {SDRAM_DQ[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[10]}]
set_property PACKAGE_PIN M20 [get_ports {SDRAM_DQ[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[11]}]
set_property PACKAGE_PIN N18 [get_ports {SDRAM_DQ[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[12]}]
set_property PACKAGE_PIN N20 [get_ports {SDRAM_DQ[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[13]}]
set_property PACKAGE_PIN M16 [get_ports {SDRAM_DQ[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[14]}]
set_property PACKAGE_PIN L15 [get_ports {SDRAM_DQ[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SDRAM_DQ[15]}]

set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 25 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets tsconf/CPU/cpu_goran/alu_flags_/DFFE_inst_latch_sf_reg_0]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets tsconf/CPU/cpu_goran/alu_flags_/flags_xf_reg_0]



connect_debug_port u_ila_0/clk [get_nets [list SYNTHESIZED_WIRE_1]]
connect_debug_port u_ila_0/probe0 [get_nets [list {tsconf/CPU/a[0]} {tsconf/CPU/a[1]} {tsconf/CPU/a[2]} {tsconf/CPU/a[3]} {tsconf/CPU/a[4]} {tsconf/CPU/a[5]} {tsconf/CPU/a[6]} {tsconf/CPU/a[7]} {tsconf/CPU/a[8]} {tsconf/CPU/a[9]} {tsconf/CPU/a[10]} {tsconf/CPU/a[11]} {tsconf/CPU/a[12]} {tsconf/CPU/a[13]} {tsconf/CPU/a[14]} {tsconf/CPU/a[15]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list {tsconf/CPU/d[0]} {tsconf/CPU/d[1]} {tsconf/CPU/d[2]} {tsconf/CPU/d[3]} {tsconf/CPU/d[4]} {tsconf/CPU/d[5]} {tsconf/CPU/d[6]} {tsconf/CPU/d[7]}]]

